### ISSUE TITLE
Online Plot Capacity shows too little plots - need support please

### ISSUE THREAD

**Issue by monteray99** [hpool-dev/chia-miner#539]
Hy,

i have a problem.

My Online Miner shows the correct TB-data , around 58TB at 5 drives.
In the GUI (1.4.0-2) all 5 HDDs working effective

But Online Plot and Contribution only show 11TB , only 119 plots are signed and no more displayed. but i have about 600.
Also my revenue  is only for 11TB

Please help me , what can i do?

**Comment by Wontell** [comment]
Can confirm, same issue, 85TB online, but only ONE plott file signed and 0 unsigned plots

**Comment by CRISPRCUT** [comment]
same here

**Comment by Exzellenz** [comment]
Same here:
 Mining on 2 machines  with 2 Different Locations and  Ip Adresses  Same Version and config on both the smaller one with arround 40 tb shows plots signed, the other 100tb was unsigned before and now disappeard completly in online plots only showing in online Miners

**Comment by jeppsp** [comment]
Same here, pool is dead once again, I'll plot solo.

**Comment by mile1020** [comment]
same problem here.  I am using the last version since 26th. After 0:00, there are only 18T online and signed; the other 52TB are online but unsigned.

**Comment by Terran976** [comment]
Same problem. Only 8 tb showing, no revenue, 32 tb in miner, dont understand whats happening.

Have i just to stop mining and go another pool?
![изображение](https://user-images.githubusercontent.com/84562805/120248288-2e65f100-c27f-11eb-9ab2-b24c9d641821.png)
![изображение](https://user-images.githubusercontent.com/84562805/120248296-358cff00-c27f-11eb-8024-61d6da9e260e.png)
![изображение](https://user-images.githubusercontent.com/84562805/120248306-3f166700-c27f-11eb-8e8e-761fbdc21c1c.png)

**Comment by Wontell** [comment]
Did anyone here tried to re-do everything from 0?
Delete the old signature and start from beginning?

**Comment by Wontell** [comment]
fixed, works fine now

**Comment by monteray99** [comment]
how?

**Comment by Terran976** [comment]
> 
> 
> fixed, works fine now

Did you just rebend it?

**Comment by brettman422** [comment]
I am having the same problem: No online plots are showing up.  My miners are online showing 40TB but my online plots screen still shows nothing after 8 hours.  I even made sure that the log files were clear of errors.  Yes, I made sure to generate a new signature and bind that in the online configuration.  My fingerprint matches so I know I got it correct.  My sweep times are never more than 0.5s which is clearly under 5s.  I am using the latest version 1.4.0-2 for windows both console and GUI have same results.

**Comment by Terran976** [comment]
![Снимок2](https://user-images.githubusercontent.com/84562805/120253680-b1dc0e00-c290-11eb-8fd9-0d29417031d7.PNG)
Suddenly it got normal by itself. I did nothing for this.

**Comment by monteray99** [comment]
still the same problem , online plots only show 119 instead of all my 600 plots

**Comment by sbaldin** [comment]
The same problem for me I have only 3 online plots instead of 50.

**Comment by oktaysar16** [comment]
Same... 238 plots signed but the other 63 plots still unsigned.

**Comment by BigUncle** [comment]
Same problem.
![image](https://user-images.githubusercontent.com/9360607/120261955-8c202a80-c2cb-11eb-8513-dc9f6222cbc6.jpeg)

**Comment by xicexice** [comment]
垃圾黑心矿池偷我们算力

**Comment by monteray99** [comment]
After several ours it adds plots...57TB from 67TB so far...

**Comment by zeybor** [comment]
after more than 12 hours only 1 plot is displyed on the online plots section out of 820 plots. they displyed correctly in the miner gui.

**Comment by monteray99** [comment]
it just needs time guys , let it settle

**Comment by xysubskyline** [comment]
Ive same issua guys please helpp  :(:(:(:( Im seeing 9,71 TIB at Online Miners page , but at online plot page there is only 58 plot...But at miners i can see 9,71 TIB and all my plots...What the heckkk ??

**Comment by bertybassett** [comment]
same here farm is 91Tb but only 40TB of plots shown, getting about 10Tb added each day.

**Comment by Wontell** [comment]
> Ive same issua guys please helpp :(:(:(:( Im seeing 9,71 TIB at Online Miners page , but at online plot page there is only 58 plot...But at miners i can see 9,71 TIB and all my plots...What the heckkk ??

Stop whining, cant you read what others said? You need to wait thats it

**Comment by medojoe** [comment]
> > Ive same issua guys please helpp :(:(:(:( Im seeing 9,71 TIB at Online Miners page , but at online plot page there is only 58 plot...But at miners i can see 9,71 TIB and all my plots...What the heckkk ??
> 
> Stop whining, cant you read what others said? You need to wait thats it

waiting will not solve it .. didn't for me

**Comment by bertybassett** [comment]
found an easy fix. moved to https://core-pool.com

**Comment by bertybassett** [comment]
> > Ive same issua guys please helpp :(:(:(:( Im seeing 9,71 TIB at Online Miners page , but at online plot page there is only 58 plot...But at miners i can see 9,71 TIB and all my plots...What the heckkk ??
> 
> Stop whining, cant you read what others said? You need to wait thats it

stop whining about people whining when those whining are not whining but have genuine problems.  I waited over 36 hours no dice.

**Comment by kondalyej** [comment]
Same problem.
